/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Point = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : IDL.Nat,
  'name' : IDL.Text,
});
export const Region = IDL.Record({
  'x' : IDL.Float64,
  'y' : IDL.Float64,
  'id' : IDL.Nat,
  'height' : IDL.Float64,
  'name' : IDL.Text,
  'width' : IDL.Float64,
});

export const idlService = IDL.Service({
  'addPoint' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [IDL.Nat], []),
  'addRegion' : IDL.Func(
      [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
      [IDL.Nat],
      [],
    ),
  'deletePoint' : IDL.Func([IDL.Nat], [], []),
  'deleteRegion' : IDL.Func([IDL.Nat], [], []),
  'getPoints' : IDL.Func([], [IDL.Vec(Point)], ['query']),
  'getRegions' : IDL.Func([], [IDL.Vec(Region)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Point = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : IDL.Nat,
    'name' : IDL.Text,
  });
  const Region = IDL.Record({
    'x' : IDL.Float64,
    'y' : IDL.Float64,
    'id' : IDL.Nat,
    'height' : IDL.Float64,
    'name' : IDL.Text,
    'width' : IDL.Float64,
  });
  
  return IDL.Service({
    'addPoint' : IDL.Func([IDL.Text, IDL.Float64, IDL.Float64], [IDL.Nat], []),
    'addRegion' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Float64, IDL.Float64, IDL.Float64],
        [IDL.Nat],
        [],
      ),
    'deletePoint' : IDL.Func([IDL.Nat], [], []),
    'deleteRegion' : IDL.Func([IDL.Nat], [], []),
    'getPoints' : IDL.Func([], [IDL.Vec(Point)], ['query']),
    'getRegions' : IDL.Func([], [IDL.Vec(Region)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };